name: Build and Test

on: ["push", "pull_request"]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}